export const GET_ALLTASK_SUCCESS = "GET_ALLTASK_SUCCESS";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const UPDATED_TASK_BY_PUSHER_SUCCESS = "UPDATED_TASK_BY_PUSHER_SUCCESS";

export const TASK_FAILURE = "TASK_FAILURE";
export const TASK_REQUEST = "TASK_REQUEST";
